spring:
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  config:
    import: optional:secrets.yml
  # ==============================================================
  # = Data Source
  # ==============================================================
  datasource:
    # url: jdbc:mysql://localhost:3307/real_estate
    # username: real_estate
    # password: your_password_here
    # url: jdbc:mysql://localhost:3306/real_estate
    # username: root
    # password:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: real-estate-spring-boot
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ==============================================================
  # = Hibernate ddl auto (create, create-drop, update)
  # ==============================================================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false
    secretsmanager:
      enabled: true
    secret-name: prod/realestateapp
    region:
      static: ap-southeast-1

application:
  bucket:
    name: huy-property-images
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
